<!-- This file is not meant to be knitted as standalone. The necessary options and latex packages are included in thesis_paper.Rmd. Pls compile thesis_paper.Rmd directly. This file is created just for separately placing one section. It serves no other purpose!-->


# Disagreement and Returns {#sec:disagree_and_ret}

Several papers have documented the positive relationship between some form of illiquidity (bid-ask spread, Amihud's measure, trading volume) and returns. \cite{amihud_mendelson1986} find that expected returns are increasing in the relative spread and the spread adjusted return increases with the holding period. In equilibrium a clientele effect emerges where higher spread assets are held by investors with higher holding period to take advantage of the higher return. \cite{brennan_etal1998} find several non-risk security characteristics like trading volume to be strongly related with stock returns. In particular a stock with high turnover earns lower returns than a stock with low turnover. \cite{chordia_etal2001} reaffirm the negative turnover return relationship and find that expected returns are negatively related not only to level of liquidity but also to its variability.

Illiquidity premium arises since a thinly traded stock is difficult to turn around[^turn_around]. There is an additional risk in holding such a stock in case liquidation is required. Hence investors demand extra premium for bearing the additional risk. \cite{jfqa_liquidity2015} propose two types of illiquidity premia: characteristic and systematic. Characteristic illiquidity is the price impact of trade and stems from the transaction costs. Systematic illiquidity captures a stock's sensitivity to market wide illiquidity (\cite{pastor_and_stambaugh2003}).

[^turn_around]: Turn around means buying and selling a stock. Illiquidity can be measured by the price paid for such a round trip transaction (bid-ask spread).

Regression results from section \ref{sec:results} show a consistent and positive disagreement volume relationship. Disagreement, measured by the standard deviation of the trading signals generated by return anomalies significantly explains next period trading volume. Since the return anomalies are contructed from publicly available accounting and stock price data, disagreement captures the differential interpretation of common information. A natural question to ask is whether disagreement explains a part of negative turnover return relationship? This is the first hypothesis I evaluate.

The debate on disagreement-return relation is unsettled with evidence of positive relationship in \cite{miller1977} and negative relationship in \cite{williams1977}. \cite{miller1977} argues that a stock with high disagreement will cause mispricing from both optimists and pessimists. But due to short sale constraints, pessimists will sit out and the stock price will reflect only the position of optimists. \cite{williams1977} on the other hand argues that a stock with higher disagreement can lead to higher adverse selection costs and investors thus demand compensation for bearing the additional costs leading to higher expected returns. Using data from the MBS market, \cite{carlin_etal2014} find evidence for the risk hypothesis and ascertain rational expectations (RE) mechanism to be the channel through which disagreement affects asset prices. Thus, as a second hypothesis, I examine the disagreement-return relationship using the new measure of disagreement.

\cite{banerjee2011} combines rational expectations (RE) and difference in opinion (DO) approach to study the return-volume characteristics as disagreement among agents varies. In a RE model, investors condition on prices to learn about private information of others while in a DO model investors held their own beliefs credible and do not condition on prices. Disagreement can have a different relationship with risk based on the model. In RE model higher disagreement makes investors condition on prices more aggressively since there is much more to be learnt about other investor's private information. As a result, prices are more sensitive to asset payoffs and higher disagreement increases perceived risk causing investors to demand higher expected returns. Alternatively, in a DO model, more disagreement means investors hold their beliefs more credibly and disregard any information in prices. This makes prices less sensitive to asset payoffs and higher disagreement is related to lower expected returns. More recently \cite{fischer_ssrn2019} demarcate information asymmtery from disagreement using analyst forecasts and find that their measure of disagreement is positively related to contemporaneous returns.



## Turnover Return Relationship {#sec:trunover-return-relationship}

In section \ref{sec:results} we have established a strong disagreement-turnover relationsip and a part of turnover is explained by disagreement. I want to investigate whether this effect propogates the trunover-return relationship as well. And if it does, is the effect similar for all disagreement levels? Like disagreement-turnover regressions, the turnover-return regressions are also predictive cross-section regressions where all explanatory variables are one period lagged values. To maintain the consistency of the predictive framework across disagreement-turnover relation where turnover is a dependent variable and turnover-return relation where turnover is an explanatory variable; I lag disagreement by two periods. Thus return is regressed on one period lagged controls, one period lagged turnover and two period lagged disagreement.

Figure \ref{fig:return_over_trun_and_dev_deciles} gives a visual account of aevrage returns over turnover and disagreement deciles. I plot five excess return measures: return minus risk free return, CAPM alpha, FF3 alpha, FFC ^[\cite{fama_french1992} complemented with the momentum factor of \cite{carhart1997}] alpha and FF5 alpha. Turnover decile are constructed in the previous month while the disagreement deciles are from two months ago. In both the subplots, excess return falls dramatically in the last decile. Excess return gradually falls for the first six turnover deciles, then flattens for next three deciles and finally falls in the tenth decile. On the other hand, for disagreement deciles, excess return at first gradually rises for the first five deciles then starts falling for the next three deciles and finally plummets for the last two deciles. The fall is particularly sharp for the last decile where excess returns decrease by 6-7% per annum. Thus we get a priliminary evidence for both risk and short-sale hypothesis of how disagreement affects returns.

<!-- Insert Figure! -->
`r rmd_print_figure("../../return_over_trun_and_dev_deciles.pdf", skip = exclude_sections$disagreement_and_returns)`



## Disagreement Return Relationship {#sec:disagreement-return-relationship}

Next, I present univariate sorts of excess returns using tunrover and disagreement deciles. Table \ref{tab:univariate_sorts_return_1} presents successive decile changes of excess returns as we move from first turnover decile to last decile. Few points are worth noting: 1) decile changes are mostly negative and significant, 2) excess return changes are relatively weaker in later half od deciles, and, 3) excess returns fall sharply in the tenth decile. Thus there is a strong evidence of negative turnover return relationship. Table \ref{tab:univariate_sorts_return_2} presents a similar analysis for disagreement deciles. Some observations are: 1) decile changes are positive and significant to begin with, 2) in the middle deciles the changes are mostly insignificant and indistinguishable from zero, 3) changes become increasingly negative as we move to even higher disagreement deciles, and, 4) finally plummet in the last decile. The first few decile changes give some support for the risk hypothesis where excess returns tend to increase with disagreement due to increased adverse selection cost. The later decile support the difference in opinion (DO) view where increased disagreement cause lower returns. Although the debate of what explains disagreement-risk relationship is still unsettled, the evidence from univariate sorts provide a much stronger economic support for the DO (short-sale) hypothesis as the magnitude of return decline (in later deciles) are much larger than the magnitude of return advances (in earlier deciles).

<!-- Insert Table! -->
`r rmd_print_table("../tables/tab_univariate_sorts_return_1.tex.RData", skip = exclude_sections$disagreement_and_returns);`

<!-- Insert Table! -->
`r rmd_print_table("../tables/tab_univariate_sorts_return_2.tex.RData", skip = exclude_sections$disagreement_and_returns);`

In the next set of tables, I present predictive return regression where alpha from \cite{fama_french2015} five-factor model is regressed on a set of controls (firm size, book to market, stock price level, short-term momentum, lagged momentum), turnover, variability in turnover ^[$STD\_TURN$ is the standard deviation of turnover from time $t$ to $t-35$, i.e. it is a 36 month rolling window standard deviation.], forecast dispersion and the disagreement measure. The controls are taken from \cite{brennan_etal1998}, turnover variability is proposed in \cite{chordia_etal2001} and forecast dispersion from \cite{diether_etal2002}. Table \ref{tab:disagreement_return_reg_1} illustrates different combination of controls, turnover, forecast dispersion and disagreement. The dependent variable is FF5 alpha in annualized percentages. Specification (2) is the main regression from \cite{chordia_etal2001} and comparing it with specification (1) shows that turnover and its variability are negatively related to future returns consistent with prior literature. We see a decent increase in R^2^ as well between specs 1 and 2. Forecast dispersion has a consistent negative relation (specs 3, 6 and 8) with future returns inline with the findings in \cite{diether_etal2002}.

However, using just the disagreement in spec (4) gives insignificant coefficient and no increase in R^2^ w.r.t. spec (1), hinting that disagreement mayn't be related to future returns. The results from univariate sorts hinted of a non-linear relationship between returns and disagreement. To validate this, in specs 5, 7 and 8, I also include the square of disagreement in the regression equation. Comparing these with specs 1, 2 and 6 shows that R^2^ increases after including disagreement and its square term in the regression. The coefficient on $STD\_DEV$ is positive and on $STD\_DEV^2$ is negative, suggesting that the relationship between disagreement and returns is positive for smaller values of $STD\_DEV$ and negative for larger values. The evidence in Table \ref{tab:disagreement_return_reg_1} is broadly consistent with the univariate sort results from Table \ref{tab:univariate_sorts_return_2}. The regression coefficinets aren't very useful for interpretation since the two regressors (disagreement and its square) are highly correlated. Inclusion of disagreement reduces coefficients on size, stock price and standard deviation of turnover. The coefficient on turnover doesn't vary much (specs 2 and 7) which may be an indication that turnover and disagreement affect returns trhough different channels. Although inclusion of forecast dispersion substantially reduces the coefficient on turnover as well as makes variability of turnover insignificant (spec 2 and 6). Thus forecast dispersion does explain a part of turnover return relationship studied in \cite{chordia_etal2001}.

<!-- Insert Table! -->
`r rmd_print_table("../tables/tab_disagreement_return_reg_1.tex.RData", skip = exclude_sections$disagreement_and_returns);`

Table \ref{tab:disagreement_return_reg_2} repeats specifications 2, 6, 7 and 8 of Table \ref{tab:disagreement_return_reg_1} using different dependent variable: CAPM alpha and FF3 alpha (\cite{fama_french1992}). The findings from \ref{tab:disagreement_return_reg_1} are reinforced with different measures of excess returns: inclusion of disagreement and its square results in improvement of R^2^; coefficient on turnover falls after including forecast dispersion or disagreement or both (except for spec 4); coefficient on turnover variability falls but doesn't become insignificant unlike with FF5 alpha (in Table \ref{tab:disagreement_return_reg_1}). Inclusion of forecast dispersion substantially reduces the magnitude of coefficients on disagreement and its quared term. Here also, a precise interpretation of the effect of disagreement can't be made due to multi-collinearity between the two disagreement terms.

<!-- Insert Table! -->
`r rmd_print_table("../tables/tab_disagreement_return_reg_2.tex.RData", skip = exclude_sections$disagreement_and_returns);`

To further investigate the disagreement/return relationship and alleviate the multi-collinearity arising due to inclusion of disagreement and its squared value, I use disagreement decile dummies in place of disagreement level in the combined regression category and limit the sample to one particular disagreement decile in separate regression category of Table \ref{tab:disagreement_return_reg_size_terciles}. Annualized FF5 alpha is regressed on controls, turnover, forecast dispersion and disagreement. There is no squared disagreement term. Only the coefficients for disagreement (or its decile dummy) are shown. There are two sets of regressions: combined regression is a single regression which includes ten disagreement decile dummy variables while separate regression constitute ten separate regression where for each regression the sample is restricted to one particular disagreement decile. The explanatory variable in separate regressions is raw disagreement.

For the three rows of combined regression category, the coefficient on $STD\_DEV\_Dec_{t-2}$ increases steadily for the first seven deciles and then starts declining. The first decile is subsumed by the fixed effect dummies and hence not reported. The coefficients can be interpreted as the change in FF5 alpha as we move from first disagreement decile to another decile. All disagreement deciles are significant in explaianing returns. in the tenth decile, coefficient falls by a lot and becomes negative in the first two rows. For smaller levels of disagreement the relationship is positive and the effect reduces as we move to higher disagreement deciles. For extremely large values of disagreement, the relationship turns negative. When forecast dispersion is included, the disagreement-return relationship remains positive for all deciles. Although the squared regressands in Table \ref{tab:disagreement_return_reg_1} capture the non-linear relationship of disagreement and returns, the first two rows of Table \ref{tab:disagreement_return_reg_size_terciles} further elaborate the mechanism of the observed non-linearity where the relationship turns significantly negative for the last disagreement decile.

Finally, the separate regression category in Table \ref{tab:disagreement_return_reg_size_terciles} illustrates coefficient estimate of disagreement from ten separate regressions where the sample is restricted to one particular disagreement decile. For the first two rows (i.e. without forecast dispersion), the coefficient is positive, significant and increasing for the first four deciles, then turns insignificant for the next 4 deciles only to become large, negative and significant for the last two deciles. In second row, from first to fourth decile the coefficient goes from 6.5 to 25 while for the ninth and tenth decile the coefficients are -33.3 and -46.1 respectively. The effect of disagreement on returns for the last decile is almost seven times as large in magnitude as the first decile. For comparision the coefficient in the specification 4 of Table \ref{tab:disagreement_return_reg_1} is only -1.6 that too without statistical significance. The apparent structure in the sign and magnitude of coefficinet explains why the coefficient in the full sample is very small and insignificant. The large negative effect of the last two deciles is balanced by the positive effect of first four deciles. For the third row, similar structure emerges except for the large negative disagreement return relationship evident in first two rows. The negative disagreement-return relationship present for large level of disagreement, disappears when forecast dispersion is added to the regression specification (thrid row of both categories). Thus disagreement as measured by the standard deviation of return anomaly signals explains the risk hypothesis where higher disagreement is related to higher future returns and forecast dispersion explains the differences in opinion hypothesis where higher disagreement is related to low future returns. 

<!-- Insert Table! -->
`r rmd_print_table("../tables/tab_disagreement_return_reg_size_terciles.tex.RData", skip = exclude_sections$disagreement_and_returns);`

Table \ref{tab:disagreement_return_reg_short_sale} and \ref{tab:disagreement_return_reg_disagreement_terciles}.


<!-- Insert Table! -->
`r rmd_print_table("../tables/tab_disagreement_return_reg_short_sale.tex.RData", skip = exclude_sections$disagreement_and_returns);`


<!-- Insert Table! -->
`r rmd_print_table("../tables/tab_disagreement_return_reg_disagreement_terciles.tex.RData", skip = exclude_sections$disagreement_and_returns);`



Tables \ref{tab:bivariate_sorts_return_1} and \ref{tab:bivariate_sorts_return_3} presents bivariate dependent sorts using terciles of control varibales and then $STD\_DEV_{t-2}$. The control varibales are the same as in specification 6 of Table \ref{tab:disagreement_return_reg_1}. FF5 alpha is averaged over different 3 $\times$ 3 portfolio terciles constucted using one of the eight controls as the first sorting variable and then disagreement as the second sorting variable. Within second and third control tercile (the three broad columns labelled $Control\_Var\_Ter_{(i,.)}, i \in 1,2,3$) return increases from first disagreement tercile to second tercile and then falls as we move from second tercile to third tercile. In the first control tercile, the evidence is mixed while moving from first disagreement tercile to second. The first effect is weaker than the second both in terms of sign of return change and the magnitude. This further proves the presence of both risk hypothesis and difference in opinion hypothesis as the mechanism of how disagreement affects returns. The change in returns are economically significant as well. For instance, in the third book to market tercile, as we move from second disagreement tercile to third tercile the average FF5 alpha falls more than 8% annually. It is worthwhile to note that within forecast dispersion terciles, the negative return effect of moving from second disagreement tercile to third is substantially weakened.


<!-- Insert Table! -->
`r rmd_print_table("../tables/tab_bivariate_sorts_return_1.tex.RData", skip = exclude_sections$disagreement_and_returns);`

<!-- Insert Table! -->
`r rmd_print_table("../tables/tab_bivariate_sorts_return_3.tex.RData", skip = exclude_sections$disagreement_and_returns);`











